image: sahilseth/r-devel


# install the package and dependencies:
# - create directory for R libraries (if not already exists)
# - create .Renviron with location of R libraries
# - define R repository in .Rprofile
# - add .travis.yml to .Rbuildignore
# - install devtools if not already installed
# - install covr if not already installed
# - update all installed packages
# - install package with dependencies

test:
  before_script:
    - mkdir -p ~/Rlib
    - echo 'R_LIBS=~/Rlib' > .Renviron
    - echo 'options(repos = "http://cran.rstudio.com")' > .Rprofile
    - echo '.gitlab-ci.yml' > .Rbuildignore
    - Rscript -e 'if(!"devtools" %in% rownames(installed.packages())) { install.packages("devtools", dependencies = TRUE) }'
    - Rscript -e 'if(!"covr" %in% rownames(installed.packages())) { install.packages("covr", dependencies = TRUE) }'
    - Rscript -e 'if(!"lintr" %in% rownames(installed.packages())) { install.packages("lintr", dependencies = TRUE) }'
    - Rscript -e 'update.packages(ask = FALSE, instlib = "~/Rlib")'
    - Rscript -e 'devtools::install_deps(pkg = ".", dependencies = TRUE)'
  script:
    - R CMD build . --no-build-vignettes --no-manual
    - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    - R CMD check "${PKG_FILE_NAME}" --no-build-vignettes --no-manual --as-cran
    - Rscript -e "library('lintr'); lint_package()"
